### ISSUE TITLE
Assist tracking

### ISSUE THREAD

**Issue by CarpeSwag** [stephenfournier/dotastrikers#107]
We really need to get this in. I'll probably try to work on this when I get time. The most important thing though is how do we display who gets assists. Do we just put it under?

For example, something like 
"Myll has scored! 
Assists: Soleone, Kobb"

Or just keep them on the same line and call it a day?

**Comment by KobbDota** [comment]
I'd say keep it in the same format as the first line, as in a full sentence. So for example:

Myll has scored!
Assited by Soleone and Kobb.
