### ISSUE TITLE
scoreboard in panorama

### ISSUE THREAD

**Issue by stephenfournier** [stephenfournier/dotastrikers#82]
in overthrow there's a button on the far left, that when clicked brings out info about the game.

for the scoreboard i'd like a button similar to this but on the far right. when clicked it would bring out a "minimized version" of the scoreboard with only the most important stats. This minimized scoreboard would then have a similar button that can extend it to the full featured scoreboard. i'll try and make a mock up of what i'm talking about.

i'll update this issue in the future to describe the stats i can send to the scoreboard from lua.

**Comment by CarpeSwag** [comment]
Pretty much done, just needs to be uploaded to a live version.
